#!/bin/python3

N = int(input())
if (N % 2) == 1:
    print("Weird")
elif ((N <= 5) & (N >= 2)):
    print ("Not Weird") 
elif ((N <= 20) & (N >= 6)):
    print ("Weird")
elif (N > 20):
    print ("Not Weird")
